# Generated by Django 6.1.2 on 2026-10-06 15:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asegurado',
            fields=[
                ('id_asegurado', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('national_id', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('direccion', models.TextField(blank=True)),
                ('kyc_status', models.CharField(choices=[('pendiente', 'Pendiente'), ('verificado', 'Verificado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'asegurado',
                'indexes': [models.Index(fields=['national_id'], name='idx_asegurado_national_id')],
                'constraints': [models.CheckConstraint(condition=models.Q(('kyc_status__in', ['pendiente', 'verificado', 'rechazado'])), name='chk_asegurado_kyc_status')],
            },
        ),
        migrations.CreateModel(
            name='DocKyc',
            fields=[
                ('id_doc', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(max_length=50)),
                ('documento_url', models.TextField()),
                ('verificado_en', models.DateTimeField(blank=True, null=True)),
                ('asegurado', models.ForeignKey(db_column='id_asegurado', on_delete=django.db.models.deletion.CASCADE, related_name='documentos_kyc', to='asegurados.asegurado')),
            ],
            options={
                'db_table': 'doc_kyc',
                'indexes': [models.Index(fields=['asegurado'], name='idx_doc_kyc_asegurado')],
            },
        ),
    ]
